import type { DashboardData } from './types';

// Helper to get current time info
const now = new Date();
const currentHour = now.getHours();

export const mockDashboardData: DashboardData = {
  // Location Info
  locationId: 'loc_001',
  locationName: 'Downtown Salon & Spa',
  isOpen247: false,
  isCurrentlyOpen: currentHour >= 9 && currentHour < 20,
  workingHours: [
    { day: 'Monday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
    { day: 'Tuesday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
    { day: 'Wednesday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
    { day: 'Thursday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
    { day: 'Friday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
    { day: 'Saturday', isOpen: true, openTime: '10:00', closeTime: '18:00' },
    { day: 'Sunday', isOpen: false },
  ],

  // Today's Overview
  todayAppointments: {
    pending: 3,
    confirmed: 8,
    completed: 12,
    no_show: 1,
    cancelled: 2,
  },
  nextAppointment: {
    id: 'apt_001',
    customerName: 'Sarah Johnson',
    customerAvatar: undefined,
    serviceName: 'Haircut & Styling',
    staffName: 'Maria Garcia',
    staffAvatar: undefined,
    time: '14:30',
    duration: 45,
    price: 65,
  },
  revenueToday: 1420,
  staffAvailableToday: 4,
  staffLoadPercentage: 68,
  staffOnDuty: [
    {
      id: 'staff_001',
      name: 'Maria Garcia',
      role: 'Senior Stylist',
      isOnDuty: true,
      appointmentsToday: 6,
      bookedMinutes: 270,
      availableMinutes: 480,
      rating: 4.9,
      reviewCount: 127,
    },
    {
      id: 'staff_002',
      name: 'James Wilson',
      role: 'Colorist',
      isOnDuty: true,
      appointmentsToday: 4,
      bookedMinutes: 360,
      availableMinutes: 480,
      rating: 4.7,
      reviewCount: 89,
    },
    {
      id: 'staff_003',
      name: 'Emma Thompson',
      role: 'Nail Technician',
      isOnDuty: true,
      appointmentsToday: 8,
      bookedMinutes: 320,
      availableMinutes: 480,
      rating: 4.8,
      reviewCount: 156,
    },
    {
      id: 'staff_004',
      name: 'Michael Chen',
      role: 'Massage Therapist',
      isOnDuty: true,
      appointmentsToday: 5,
      bookedMinutes: 300,
      availableMinutes: 480,
      rating: 4.9,
      reviewCount: 203,
    },
  ],

  // Appointment Metrics
  weeklyAppointments: {
    pending: 12,
    confirmed: 34,
    completed: 78,
    no_show: 4,
    cancelled: 8,
  },
  weeklyLoadPercentage: 72,
  monthlyAppointments: {
    pending: 45,
    confirmed: 120,
    completed: 342,
    no_show: 18,
    cancelled: 35,
  },
  monthlyLoadPercentage: 65,
  bookingSources: [
    { source: 'marketplace', count: 156, percentage: 45 },
    { source: 'admin', count: 89, percentage: 26 },
    { source: 'phone', count: 72, percentage: 21 },
    { source: 'walk_in', count: 28, percentage: 8 },
  ],
  noShowRate: 5.2,
  cancellationRate: 10.1,
  averageDuration: 52,

  // Revenue Analytics
  revenueThisWeek: 8450,
  revenueThisMonth: 34280,
  revenueLastMonth: 31540,
  averageTicketValue: 78.50,

  // Staff Performance
  staffPerformance: [
    {
      id: 'staff_001',
      name: 'Maria Garcia',
      role: 'Senior Stylist',
      isOnDuty: true,
      appointmentsToday: 6,
      bookedMinutes: 270,
      availableMinutes: 480,
      rating: 4.9,
      reviewCount: 127,
    },
    {
      id: 'staff_002',
      name: 'James Wilson',
      role: 'Colorist',
      isOnDuty: true,
      appointmentsToday: 4,
      bookedMinutes: 360,
      availableMinutes: 480,
      rating: 4.7,
      reviewCount: 89,
    },
    {
      id: 'staff_003',
      name: 'Emma Thompson',
      role: 'Nail Technician',
      isOnDuty: true,
      appointmentsToday: 8,
      bookedMinutes: 320,
      availableMinutes: 480,
      rating: 4.8,
      reviewCount: 156,
    },
    {
      id: 'staff_004',
      name: 'Michael Chen',
      role: 'Massage Therapist',
      isOnDuty: true,
      appointmentsToday: 5,
      bookedMinutes: 300,
      availableMinutes: 480,
      rating: 4.9,
      reviewCount: 203,
    },
    {
      id: 'staff_005',
      name: 'Sophie Brown',
      role: 'Junior Stylist',
      isOnDuty: false,
      appointmentsToday: 0,
      bookedMinutes: 0,
      availableMinutes: 0,
      rating: 4.5,
      reviewCount: 34,
    },
  ],
  calendarBlocksByStaff: [
    { id: 'block_001', title: 'Vacation', scope: 'staff', staffName: 'Sophie Brown', startTime: '2026-01-29', endTime: '2026-02-02', reason: 'vacation' },
    { id: 'block_002', title: 'Lunch Break', scope: 'staff', staffName: 'Maria Garcia', startTime: '2026-01-29T12:00', endTime: '2026-01-29T13:00', reason: 'break' },
    { id: 'block_003', title: 'Team Meeting', scope: 'location', startTime: '2026-01-30T08:00', endTime: '2026-01-30T09:00', reason: 'meeting' },
  ],

  // Reviews & Ratings
  averageRating: 4.8,
  totalReviews: 609,
  recentReviews: [
    {
      id: 'rev_001',
      customerName: 'Emily Parker',
      rating: 5,
      comment: 'Amazing service! Maria did an incredible job with my hair. Will definitely be back!',
      staffName: 'Maria Garcia',
      serviceName: 'Haircut & Styling',
      createdAt: '2026-01-28',
      response: 'Thank you so much Emily! We look forward to seeing you again!',
    },
    {
      id: 'rev_002',
      customerName: 'Tom Wilson',
      rating: 5,
      comment: 'Best massage I\'ve ever had. Michael is a true professional.',
      staffName: 'Michael Chen',
      serviceName: 'Deep Tissue Massage',
      createdAt: '2026-01-27',
    },
    {
      id: 'rev_003',
      customerName: 'Grace Lee',
      rating: 4,
      comment: 'Great color job, but had to wait 15 minutes past my appointment time.',
      staffName: 'James Wilson',
      serviceName: 'Hair Coloring',
      createdAt: '2026-01-26',
    },
    {
      id: 'rev_004',
      customerName: 'Chris Anderson',
      rating: 5,
      comment: 'Love my new nails! Emma is so talented and detail-oriented.',
      staffName: 'Emma Thompson',
      serviceName: 'Manicure & Pedicure',
      createdAt: '2026-01-25',
    },
    {
      id: 'rev_005',
      customerName: 'Rachel Green',
      rating: 4,
      comment: 'Good experience overall. Nice atmosphere and friendly staff.',
      serviceName: 'Facial Treatment',
      createdAt: '2026-01-24',
      response: 'Thanks for your feedback Rachel! We\'re glad you enjoyed your visit.',
    },
  ],
  reviewsAwaitingResponse: 3,
  ratingThisMonth: 4.8,
  ratingLastMonth: 4.7,

  // Services Analytics
  topServices: [
    { id: 'svc_001', name: 'Haircut & Styling', categoryName: 'Hair', appointmentCount: 134, revenue: 8750, isEnabled: true, bookingType: 'single' },
    { id: 'svc_002', name: 'Hair Coloring', categoryName: 'Hair', appointmentCount: 48, revenue: 7200, isEnabled: true, bookingType: 'single' },
    { id: 'svc_003', name: 'Deep Tissue Massage', categoryName: 'Massage', appointmentCount: 54, revenue: 5400, isEnabled: true, bookingType: 'single' },
    { id: 'svc_004', name: 'Manicure & Pedicure', categoryName: 'Nails', appointmentCount: 84, revenue: 4200, isEnabled: true, bookingType: 'bundle' },
    { id: 'svc_005', name: 'Facial Treatment', categoryName: 'Skincare', appointmentCount: 36, revenue: 3600, isEnabled: true, bookingType: 'single' },
    { id: 'svc_006', name: 'Full Spa Package', categoryName: 'Packages', appointmentCount: 22, revenue: 4400, isEnabled: true, bookingType: 'bundle' },
    { id: 'svc_007', name: 'Beard Trim', categoryName: 'Hair', appointmentCount: 45, revenue: 900, isEnabled: true, bookingType: 'single' },
    { id: 'svc_008', name: 'Eyebrow Threading', categoryName: 'Beauty', appointmentCount: 67, revenue: 1005, isEnabled: false, bookingType: 'single' },
  ],
  servicesByBookingType: {
    single: 384,
    bundle: 106,
  },

  // Calendar / Availability
  activeCalendarBlocks: [
    { id: 'block_001', title: 'Vacation', scope: 'staff', staffName: 'Sophie Brown', startTime: '2026-01-29', endTime: '2026-02-02', reason: 'vacation' },
    { id: 'block_003', title: 'Team Meeting', scope: 'location', startTime: '2026-01-30T08:00', endTime: '2026-01-30T09:00', reason: 'meeting' },
  ],
  staffAvailabilityToday: [
    { id: 'staff_001', name: 'Maria Garcia', role: 'Senior Stylist', isOnDuty: true, appointmentsToday: 6, bookedMinutes: 270, availableMinutes: 480, rating: 4.9, reviewCount: 127 },
    { id: 'staff_002', name: 'James Wilson', role: 'Colorist', isOnDuty: true, appointmentsToday: 4, bookedMinutes: 360, availableMinutes: 480, rating: 4.7, reviewCount: 89 },
    { id: 'staff_003', name: 'Emma Thompson', role: 'Nail Technician', isOnDuty: true, appointmentsToday: 8, bookedMinutes: 320, availableMinutes: 480, rating: 4.8, reviewCount: 156 },
    { id: 'staff_004', name: 'Michael Chen', role: 'Massage Therapist', isOnDuty: true, appointmentsToday: 5, bookedMinutes: 300, availableMinutes: 480, rating: 4.9, reviewCount: 203 },
    { id: 'staff_005', name: 'Sophie Brown', role: 'Junior Stylist', isOnDuty: false, appointmentsToday: 0, bookedMinutes: 0, availableMinutes: 0, rating: 4.5, reviewCount: 34 },
  ],

};
